 #Define the mapping of variations to the standardized value
state_mapping = {
    'CA': 'California',
    'California': 'California',
    'CALIFORNIA': 'California',
    'California ': 'California',
    'Ca': 'California',
    'ca': 'California',
    'CA - California': 'California',
    'CA ': 'California',
    'CA-California': 'California',
    'CA.': 'California',
    'Calif.': 'California',
    'California (CA)': 'California',
    ' Texas ': 'Texas',
    'TX': 'Texas',
    'Texas ': 'Texas',
    'TEXAS': 'Texas',
    'Tx': 'Texas',
    'tx': 'Texas',
    'and Texas': 'Texas',
    ' Texas': 'Texas',
    'TX ': 'Texas',
    'NY': 'New York',
    'NY ': 'New York',
    'New York': 'New York',
    'New York ': 'New York',
    'NEW YORK': 'New York',
    'New york': 'New York',
    'NY.': 'New York',
    'New York (NY)': 'New York',
    'NY - New York': 'New York',
    'IL': 'Illinois',
    'Il': 'Illinois',
    'Illinois': 'Illinois',
    'Illinois ': 'Illinois',
    'Lincolnwood, Illinois': 'Illinois',
    ' il': 'Illinois',
    ' Il': 'Illinois',
    'il': 'Illinois',
    'Ilinois': 'Illinois',
    'IL ': 'Illinois',
    'Georgia': 'Georgia',
    'GA': 'Georgia',
    'Georgia ': 'Georgia',
    'Ga': 'Georgia',
    'Georgia (GA)': 'Georgia',
    'ga': 'Georgia',
    'GA ': 'Georgia',
    'GEORGIA': 'Georgia',
    'Pennsylvania': 'Pennsylvania',
    'PA': 'Pennsylvania',
    'PA ': 'Pennsylvania',
    'PENNSYLVANIA': 'Pennsylvania',
    'Pa': 'Pennsylvania',
    'Pennsylvania ': 'Pennsylvania',
    'Florida ': 'Florida',
    'FLORIDA': 'Florida',
    'FL': 'Florida',
    'FL ': 'Florida',
    'Fl': 'Florida',
    'fl': 'Florida',
    'New Jersey': 'New Jersey',
    'NJ': 'New Jersey',
    'Massachusetts ': 'Massachusetts',
    'MA': 'Massachusetts',
    'MA ': 'Massachusetts',
    ' MA ': 'Massachusetts',
    'Ma': 'Massachusetts',
    'ma': 'Massachusetts',
    'VA': 'Virginia',
    'VA ': 'Virginia',
    'Va': 'Virginia',
    'virginia': 'Virginia',
    'Virginia ': 'Virginia',
    'MO': 'Montana',
    'Montana': 'Montana',
    'North Carolina ': 'North Carolina',
    'NC North Carolina': 'North Carolina',
    'NC': 'North Carolina',
    'N.C.': 'North Carolina',
    'Ohio': 'Ohio',
    'OH': 'Ohio',
    'WA': 'Washington',
    'WA ': 'Washington',
    'Wa': 'Washington',
    'wa': 'Washington',
    'Washington ': 'Washington',
    'Washington (WA)': 'Washington',
    'Maryland': 'Maryland',
    'MD': 'Maryland',
    'MI': 'Michigan',
    'Mi': 'Michigan',
    'mi': 'Michigan',
    'Michigan ': 'Michigan',
    'MICHIGAN': 'Michigan',
    'TN': 'Tennessee',
    'Tn': 'Tennessee',
    'TN ': 'Tennessee',
    'TENNESSEE': 'Tennessee',
    'Tennessee ': 'Tennessee',
    'DC': 'District of Columbia',
    'D.C.': 'District of Columbia',
    'District of Columbia': 'District of Columbia',
    'Washington DC': 'District of Columbia',
    'Washington D.C.': 'District of Columbia',
    'MN': 'Minnesota',
    'Minnesota': 'Minnesota',
    'Minnesota ': 'Minnesota',
    'AZ': 'Arizona',
    'Az': 'Arizona',
    'Arizona': 'Arizona',
    'CO': 'Colorado',
    'CO.': 'Colorado',
    'Co': 'Colorado',
    'co': 'Colorado',
    'Colorado': 'Colorado',
    'CT': 'Connecticut',
    'CT ': 'Connecticut',
    'ct': 'Connecticut',
    'Connecticut': 'Connecticut',
    'IN': 'Indiana',
    'In': 'Indiana',
    'in': 'Indiana',
    'Indiana': 'Indiana',
    'MO': 'Missouri',
    'mo': 'Missouri',
    'Missouri': 'Missouri',
    'WI': 'Wisconsin',
    'WI ': 'Wisconsin',
    'Wi': 'Wisconsin',
    'wi': 'Wisconsin',
    'Wisconsin': 'Wisconsin',
    'NE': 'Nebraska',
    'Nebraska': 'Nebraska',
    'SC': 'South Carolina',
    'sc': 'South Carolina',
    'SC - SOUTH CAROLINA': 'South Carolina',
    'South Carolina': 'South Carolina',
    'ON': 'Ontario',
    'Ontario': 'Ontario',
    'ONTARIO': 'Ontario',
    'Ontário': 'Ontario',
    'AR': 'Arkansas',
    'Arkansas': 'Arkansas',
    'UT': 'Utah',
    'Utah': 'Utah',
    'utah': 'Utah',
    'UTAH': 'Utah',
    'ut': 'Utah',
    'KY': 'Kentucky',
    'Ky': 'Kentucky',
    'Kentucky': 'Kentucky',
    'OR': 'Oregon',
    'Oregon': 'Oregon',
    'DE': 'Delaware',
    'Delaware': 'Delaware',
    'AL': 'Alabama',
    'Al': 'Alabama',
    'Alabama': 'Alabama',
    'NV': 'Nevada',
    'Nevada': 'Nevada',
    'KS': 'Kansas',
    'Kansas': 'Kansas',
    'IA': 'Iowa',
    'iowa': 'Iowa',
    'Iowa': 'Iowa',
    'LA': 'Louisiana',
    'La': 'Louisiana',
    'Louisiana': 'Louisiana',
    'Louisiana ': 'Louisiana',
    'OK': 'Oklahoma',
    'Ok': 'Oklahoma',
    'Oklahoma': 'Oklahoma',
    'BC': 'British Columbia',
    'British Columbia': 'British Columbia',
    'SD': 'South Dakota',
    'South Dakota': 'South Dakota',
    'ID': 'Idaho',
    'Idaho': 'Idaho',
    'NH': 'New Hampshire',
    'New Hampshire': 'New Hampshire',
    'QC': 'Québec',
    'Québec': 'Québec',
    'Quebec': 'Québec',
    'ME': 'Maine',
    'Maine': 'Maine',
    'RI': 'Rhode Island',
    'Rhode Island': 'Rhode Island',
    'HI': 'Hawaii',
    'Hawaii': 'Hawaii',
    'London': 'Greater London',
    'Greater London': 'Greater London',
    'MH': 'Maharashtra',
    'MS': 'Mississippi',
    'Ms.': 'Mississippi',
    'Mississippi': 'Mississippi',
    'NSW': 'New South Wales',
    'New South Wales': 'New South Wales',
    'ND': 'North Dakota',
    'North Dakota': 'North Dakota',
    'NM': 'New Mexico',
    'NM ': 'New Mexico',
    'New Mexico': 'New Mexico',
    'AB': 'Alberta',
    'Alberta': 'Alberta',
    'VT': 'Vermont',
    'Vermont': 'Vermont',
    'WV': 'West Virginia',
    'wv': 'West Virginia',
    'West Virginia': 'West Virginia',
    'WY': 'Wyoming',
    'WY ': 'Wyoming',
    'wy': 'Wyoming',
    'Wyoming': 'Wyoming',
    'BW': 'Baden-Württemberg',
    'Île-de-France': 'Île-de-France',
    'Ile-de-France': 'Île-de-France',
    'Ile de France': 'Île-de-France',
    'IDF': 'Île-de-France',
    'NewJersey': 'New Jersey',
    'NJ - New Jersey': 'New Jersey',
    'NJ': 'New Jersey',
    'N.J.': 'New Jersey',
    'New Jersey ': 'New Jersey',
    'NRW': 'North Rhine-Westphalia',
    'North-Rhine-Westphalia': 'North Rhine-Westphalia',
    'North Rhine-Westphalia ': 'North Rhine-Westphalia',
    'Nordrhein-Westfalen': 'North Rhine-Westphalia',
    'VIC': 'Victoria',
    'MT': 'Montana',
    'ENGLAND': 'England',
    'QLD': 'Queensland',
    'SK': 'Saskatchewan',
    'USA': 'United States',
    'UP': 'Uttar Pradesh',
    'TS': 'Telangana',
    'FRANCE': 'France',
    'United States (+1)': 'United States',
    'BVI': 'British Virgin Islands',
    'Bayern': 'Bavaria',
    'Madrid': 'Community of Madrid',
    'AK': 'Alaska',
    'none': '0',
    'UK': 'United Kingdom',
    'ZH': 'Zhengzhou',
    'FI': 'Finland',
    'Global': 'Worldwide',
    'globally': 'Worldwide',
    'Anywhere': 'Worldwide',
    'Noord-Holland': 'North Holland',
    'Noord Holland': 'North Holland',
    'Zuid-Holland': 'South Holland',
    'Zurich': 'Zürich',
    'SZ': 'Switzerland',
    'PR': 'Puerto Rico',
    'Beverly Hills': 'California',
    'worcs': 'Worcestershire',
    'KARNATAKA': 'Karnataka',
    'Golden Apple Foundation': 'Illinois',
    'NO': 'Norway',
    '广东省': 'Guangdong',
    'Sp': 'Spain',
    'md': 'Maryland',
    'Md': 'Maryland',
    'maryland': 'Maryland',
    'TV': 'Tuvalu',
    'DELAWARE (DE)': 'Delaware',
    'HM': 'Heard & McDonald Islands',
    'BS': 'Bassas da India',
    'Basel': 'Basel-Town',
    'Bassett, VA': 'Virginia',
    'CH': 'China',
    "Provence-Alpes-Cote d'Azur": "Provence-Alpes-Côte d'Azur",
    'SE': 'Seychelles',
    'Plymouth Meeting, PA, ': 'Pennsylvania',
    'Select a state': '0',
    'NS': 'Suriname',
    'NY/FL': '0',
    'ZG': '0',
    '東京都': 'Tokyo',
    '28801': '0',
    '01824': '0',
    '94086': '0',
    '85226': '0',
    '8810': '0'
    
}

# Replace the variations with the standardized value
database_aggregated['state'] = database_aggregated['state'].replace(state_mapping)

#california[['state', 'country', 'city', 'zip_code', 'address']]
